services:
  nginx:
    image: nginx:latest
    ports:
      - "5000:80"
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    container_name: app_nginx
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    restart: always
    volumes:
      - ./:/var/www/
    container_name: app
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10
    container_name: mysql


volumes:
  dbdata:
    driver: local